server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/real_estate_tracker?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.realestatetracker.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.realestatetracker: info

# 城市代码映射配置
crawler:
  city-code:
    # 贝壳网城市代码映射
    beike:
      - city: 北京
        code: bj
      - city: 上海
        code: sh
      - city: 广州
        code: gz
      - city: 深圳
        code: sz
      - city: 成都
        code: cd
      - city: 重庆
        code: cq
    # 安居客城市代码映射
    anjuke:
      - city: 北京
        code: beijing
      - city: 上海
        code: shanghai
      - city: 广州
        code: guangzhou
      - city: 深圳
        code: shenzhen
      - city: 成都
        code: chengdu
      - city: 重庆
        code: chongqing
    # 吉屋网城市代码映射
    jiwu:
      - city: 成都
        code: cd
      - city: 重庆
        code: cq
      - city: 北京
        code: bj
      - city: 上海
        code: sh
